### ISSUE TITLE
--include is broken currently

### ISSUE THREAD

**Issue by Aniketh01** [Aniketh01/abr-over-quic#3]
```

Traceback (most recent call last):
  File "player.py", line 179, in <module>
    initiate_player_event(configuration=configuration, args=args)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "player.py", line 40, in initiate_player_event
    await dc.player()
  File "/home/aniketh/devel/src/abr-over-quic/clients/dash_client.py", line 258, in player
    await self.dash_client_set_config()
  File "/home/aniketh/devel/src/abr-over-quic/clients/dash_client.py", line 116, in dash_client_set_config
    await self.download_manifest()
  File "/home/aniketh/devel/src/abr-over-quic/clients/dash_client.py", line 109, in download_manifest
    self.manifest_data = json.load(open(".cache/" + self.filename))
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by Aniketh01** [comment]
Not exactly that include argument is broken. Include basically appends the response header to the file. This broken behaviour arises when this headers are appended to the initial manifest file which is of JSON format and the JSON parser/decoder fails to parse those parameters which are basically HTTP headers and not JSON formatted. 

Hence fixed with: a4d5c6458235fe6849d974e7771cb05007c5fd1c
